GET http://localhost:3008/
###


POST http://localhost:3008/register/
Content-Type: application/json

{
   "fullname":"pavan kalyan",
   "email":"pavan573@gmail.com",
   "mobile":7434565637,
   "skills":"node.js",
   "password":"pavan12345" ,
   "confirmPassword":"pavan12345"
}
###
POST http://localhost:3008/login 
Content-Type: application/json

{
   "email":"pavan573@gmail.com",
   "password":"pavan12345"
}
###
GET http://localhost:3008/alldevelopers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRjMDJlZmQ2NmI5NjdjZjY4ZTcxMTM2IiwiaWF0IjoxNjkwODMwODA4LCJleHAiOjM3NjkwODMwODA4fQ.ExtDqH-s9u1G2748MOUh4uNPs-24rLrW4Ze60rS_X2A